  backend:
    container_name: planet_backend
    build: backend
    image: htrvolker/planets-backend:latest
    ports:
    - target: 80
      published: 8080
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    depends_on:
    - database
  
  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: planets
