pipeline {
    agent any
    environment{
    DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
    }
    stages {
        stage('Setup') {
            steps {
              sh  "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }
    }
}
